### ISSUE TITLE
OWT centos76 test fails on E3

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#161]
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: test_xeone3-centos76-service-owt_owt_getstream

1: Test command: /home/vcse/jhou5/Dockerfiles/XeonE3/centos-7.6/service/owt/shell.sh "/mnt/owt_getstream.sh" "xeone3-centos76-service-owt"
1: Test timeout computed to be: 9.99988e+06
1: #!/bin/bash -ve
1: case "$1" in
1:     *ubuntu*)
1:         apt-get update && apt-get install -y -q --no-install-recommends curl;;
1:     *centos*)
1:         yum install -y -q curl;;
1: esac
1: Package curl-7.29.0-51.el7.x86_64 already installed and latest version
1:
1: /home/launch.sh
1: about to fork child process, waiting until server is ready for connections.
1: forked process: 55
1:
1:               RabbitMQ 3.3.5. Copyright (C) 2007-2014 GoPivotal, Inc.
1:   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
1:   ##  ##
1:   ##########  Logs: /var/log/rabbitmq/rabbit@vcse-jenkins-e3.log
1:   ######  ##        /var/log/rabbitmq/rabbit@vcse-jenkins-e3-sasl.log
1:   ##########
1:               Starting broker...^[[36mHardware acceleration enabled^[[0m
1: ^[[32mInitializing ManagementAPIServer configuration...^[[0m
1:
1: /home/owt/management_api/node_modules/mongodb/lib/mongo_client.js:421
1:           throw err
1:           ^
1: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
1:     at Pool.<anonymous> (/home/owt/management_api/node_modules/mongodb-core/lib/topologies/server.js:336:35)
1:     at emitOne (events.js:116:13)
1:     at Pool.emit (events.js:211:7)
1:     at Connection.<anonymous> (/home/owt/management_api/node_modules/mongodb-core/lib/connection/pool.js:280:12)
1:     at Object.onceWrapper (events.js:317:30)
1:     at emitTwo (events.js:126:13)
1:     at Connection.emit (events.js:214:7)
1:     at Socket.<anonymous> (/home/owt/management_api/node_modules/mongodb-core/lib/connection/connection.js:189:49)
1:     at Object.onceWrapper (events.js:315:30)
1:     at emitOne (events.js:116:13)

**Comment by jhou5** [comment]
PR #167 fix this issue
