### ISSUE TITLE
Missed README auto generation for hddldaemon image 

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#446]
When run below command:

- cd build
- cmake cmake -DUPDATE_IMAGE_README=ON ..
- make

Below error shown on screen:
Scanning dependencies of target build_vcaca
Traceback (most recent call last):
  File "/home/vcse/ovc/Dockerfiles/script/generate_readme.py", line 306, in <module>
    main()
  File "/home/vcse/ovc/Dockerfiles/script/generate_readme.py", line 303, in main
    walk_path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
  File "/home/vcse/ovc/Dockerfiles/script/generate_readme.py", line 130, in walk_path
    create_readme(root, path_components)
  File "/home/vcse/ovc/Dockerfiles/script/generate_readme.py", line 298, in create_readme
    my_file.write(quick_reference(path, image_name, image_type, image_os, image_platform))
  File "/home/vcse/ovc/Dockerfiles/script/generate_readme.py", line 161, in quick_reference
    text_holder += included_components(image_name)
  File "/home/vcse/ovc/Dockerfiles/script/generate_readme.py", line 149, in included_components
    for comp in included_subs[image_name]:
KeyError: 'hddldaemon'
VCAC-A/CMakeFiles/build_vcaca.dir/build.make:57: recipe for target 'VCAC-A/CMakeFiles/build_vcaca' failed
make[2]: *** [VCAC-A/CMakeFiles/build_vcaca] Error 1
CMakeFiles/Makefile2:90: recipe for target 'VCAC-A/CMakeFiles/build_vcaca.dir/all' failed
make[1]: *** [VCAC-A/CMakeFiles/build_vcaca.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dpatel257** [comment]
This is because automated README is generated if the folder contains Dockerfile.m4
with two sepearate PR(readme generation and hddldaemon using template), this happened, fill fix it

**Comment by jhou5** [comment]
#448
