### ISSUE TITLE
OWT360 build failed

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#578]
Error Logs:
```
../MediaStream.cc: In static member function 'static void MediaStream::eventCallback(uv_async_t*)':
../MediaStream.cc:488:109: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated [-Wdeprecated-declarations]
           Nan::MakeCallback(Nan::GetCurrentContext()->Global(), obj->event_callback_->GetFunction(), 2, args);
                                                                                                             ^
In file included from ../MediaStream.h:32:0,
                 from ../MediaStream.cc:33:
../../../../../node_modules/nan/nan.h:1026:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
make: Leaving directory '/home/owt-server/source/agent/webrtc/webrtcLib/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.16
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild" "-j" "8" "--loglevel=error"
gyp ERR! cwd /home/owt-server/source/agent/webrtc/webrtcLib
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
child_process.js:650
    throw err;
    ^
 
Error: Command failed: node-gyp rebuild -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/home/owt-server/scripts/build.js:129:5)
    at buildList.map (/home/owt-server/scripts/build.js:160:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/owt-server/scripts/build.js:155:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
The command '/bin/bash -o pipefail -c git clone -b ${OWT_BRANCH} ${OWTSERVER_REPO} &&     source /opt/rh/devtoolset-7/enable &&     npm config set proxy=${http_proxy} &&     npm config set https-proxy=${http_proxy} &&     npm install -g --loglevel error node-gyp@v6.1.0 grunt-cli underscore jsdoc &&     cd ${SERVER_PATH} && npm install nan &&     cd ${SERVER_PATH}/third_party &&     mkdir openh264 && cd openh264 &&     wget ${OPENH264_SOURCE} &&     wget ${OPENH264_BINARY} &&     tar xzf ${OPENH264_SOURCENAME} openh264-${OPENH264_MAJOR}.${OPENH264_MINOR}.0/codec/api &&     ln -s -v openh264-${OPENH264_MAJOR}.${OPENH264_MINOR}.0/codec codec &&     bzip2 -d ${OPENH264_BINARYNAME}.bz2 &&     ln -s -v ${OPENH264_BINARYNAME} libopenh264.so.${OPENH264_SOVER} &&     ln -s -v libopenh264.so.${OPENH264_SOVER} libopenh264.so &&     echo 'const char* stub() {return "this is a stub lib";}' > pseudo-openh264.cpp &&     gcc pseudo-openh264.cpp -fPIC -shared -o pseudo-openh264.so &&     cd ${SERVER_PATH}/third_party && git clone ${LICODE_REPO} &&     cd licode &&     git reset --hard ${LICODE_COMMIT} &&     wget -r -nH --cut-dirs=5 --no-parent ${LICODE_PATCH_REPO} &&     git apply ${SERVER_PATH}/scripts/patches/licode/*.patch &&     mkdir -p ${SERVER_PATH}/build/libdeps/build/include &&     cp erizoAPI/lib/json.hpp ${SERVER_PATH}/build/libdeps/build/include &&     cd ${SERVER_PATH}/third_party && mkdir webrtc  && cd webrtc &&    export GIT_SSL_NO_VERIFY=1 &&     git clone -b 59-server ${WEBRTC_REPO} src && cd src &&     git reset --hard ${WEBRTC_COMMIT} &&     ./tools-woogeen/install.sh &&     ./tools-woogeen/build.sh &&     cd /home && git clone -b ${OWT_BRANCH_JS} ${OWT_SDK_REPO} && cd owt-client-javascript/scripts && git reset --hard ${OWT_BRANCH_JS_COMMIT}  && npm install && grunt  &&     export LD_LIBRARY_PATH=/usr/local/lib64 &&     cd ${SERVER_PATH} && export CPLUS_INCLUDE_PATH=/usr/local/include/svt-hevc && export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig && ./scripts/build.js -t mcu -r -c &&     ./scripts/pack.js -t all --install-module --no-pseudo --sample-path /home/owt-client-javascript/dist/samples/conference' returned a non-zero code: 1
Xeon/centos-7.6/service/owt360/CMakeFiles/build_xeon-centos76-service-owt360.dir/build.make:57: recipe for target 'Xeon/centos-7.6/service/owt360/CMakeFiles/build_xeon-centos76-service-owt360' failed
make[2]: *** [Xeon/centos-7.6/service/owt360/CMakeFiles/build_xeon-centos76-service-owt360] Error 1
CMakeFiles/Makefile2:26548: recipe for target 'Xeon/centos-7.6/service/owt360/CMakeFiles/build_xeon-centos76-service-owt360.dir/all' failed
make[1]: *** [Xeon/centos-7.6/service/owt360/CMakeFiles/build_xeon-centos76-service-owt360.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
 

```

**Comment by jhou5** [comment]
#573
